export const CFG_PREFIX = "cfg:";

export const SCREEN = {
  HOME: "home",
  CANAIS: "canais",
  EQUIPE: "equipe",
  APARENCIA: "aparencia",
  TIPOS: "tipos",
  COMPORTAMENTO: "comportamento",
  PUBLICAR: "publicar",
  LOGS: "logs",
  WELCOME: "welcome",
};

export const ID = {
  nav: `${CFG_PREFIX}nav`,
  back: `${CFG_PREFIX}back`,
  cat: `${CFG_PREFIX}cat`,
  log: `${CFG_PREFIX}log`,
  roles: `${CFG_PREFIX}roles`,
  preview: `${CFG_PREFIX}preview`,
  pubCh: `${CFG_PREFIX}pub:ch`,
  tipoSelect: `${CFG_PREFIX}tipo:select`,
  tipoAdd: `${CFG_PREFIX}tipo:add`,
  tipoEdit: `${CFG_PREFIX}tipo:edit`,
  tipoDel: `${CFG_PREFIX}tipo:del`,
  tipoDelConfirm: `${CFG_PREFIX}tipo:del:ok`,
  tipoCat: `${CFG_PREFIX}tipo:cat`,
  inact: (h) => `${CFG_PREFIX}inact:${h}`,
  inactCustom: `${CFG_PREFIX}inact:custom`,
  dmToggle: `${CFG_PREFIX}dm:toggle`,
  btnAparencia: (field) => `${CFG_PREFIX}ap:${field}`,
  apClear: `${CFG_PREFIX}ap:clear`,
  modalAparencia: (field) => `${CFG_PREFIX}modal:ap:${field}`,
  modalInact: `${CFG_PREFIX}modal:inact`,
  modalTipoAdd: `${CFG_PREFIX}modal:tipo:add`,
  modalTipoEdit: (value) => `${CFG_PREFIX}modal:tipo:edit:${value}`,
  logsCh: `${CFG_PREFIX}logs:ch`,
  logsToggle: (event) => `${CFG_PREFIX}logs:toggle:${event}`,
  welcomeCh: (type) => `${CFG_PREFIX}welcome:ch:${type}`,
  welcomeRoles: `${CFG_PREFIX}welcome:roles`,
  welcomeEdit: (type) => `${CFG_PREFIX}welcome:edit:${type}`,
  welcomeModal: (type) => `${CFG_PREFIX}welcome:modal:${type}`,
};
